# -*- coding: utf-8 -*-
{
    'name': "Recurring Subscription",
    'version': "19.0.1.0",
    'licence': "LGPL-3",
    'summary': """"Recurring Subscription designed to automate billing""",
    'description': """Recurring Subscription designed to automate billing, manage customer lifecycles, and reduce churn(description)""",
    'author': "Cybrosys",
    'website': "http://www.cybrosys.com",
    'category': 'Recurring Subscription',
    'sequence': 1,
    'application': True,
    'depends': ['base', 'product', 'mail', 'contacts', 'crm'],
    'auto_install': True,
    'data':
        ["security/security.xml",
         "security/ir.model.access.csv",
         "views/recurring_subscription_views.xml",
         "views/recurring_subscription_credit_views.xml",
         "data/recurring_subscription_sequence.xml",
         "data/mail_template_data.xml",
         "data/ir_cron_create_invoice.xml",
         "report/recurring_subscription_template.xml",
         "report/recurring_subscription_credit_template.xml",
         "report/recurring_subscription_report.xml",
         "report/recurring_subscription_credit_report.xml",
         "wizard/subscription_report_views.xml",
         "wizard/subscription_credit_report_views.xml",
         "views/recurring_billing_schedule_views.xml",
         "views/website_form.xml",
         "views/website_credit_form.xml",
         "views/website_home_views.xml",
         "views/website_billing_schedule.xml",
         "views/website_billing_schedule_portal.xml",
         "views/subscription_portal.xml",
         "views/credit_portal.xml",
         "views/recurring_partner_account.xml",
         "views/res_partner_views.xml",
         "views/crm_lead_views.xml",
         "views/account_move_views.xml",
         "views/recurring_subscription_menu_views.xml",
         ],
    'demo': ['demo/subscription_product_demo.xml']
}
